### PR TITLE
Fix for OptionalAssert.contains() not working for primitive arrays (i…

### PR DESCRIPTION
**Pull request by chrisly42**
Fix for OptionalAssert.contains() not working for primitive arrays (issue #42).

### CODE REVIEW

**Comment by joel-costigliola** [comment]
Thanks, I will review your PR shortly !

**Comment by joel-costigliola** [comment]
Integrated thanks ! I won't close this straight away as I also changed assertj-core `AbstractAssert` to make `objects` visible for subclasses which won't need anymore to define their own field.

I'll release the next version of assertj-guava after assertj-core 3.14.0 is released which should ahppen in 2 or 3 weeks.

**Comment by chrisly42** [comment]
Thanks for the quick reaction. Also, I think that your approach is favourable. Keep up the good work!

**Comment by joel-costigliola** [comment]
Integrated thanks @chrisly42!

**Pull request closed without merging**
