### PR TITLE
Add assertions for Multiset count

### PR DESCRIPTION
**Pull request by mdaniline**

### CODE REVIEW

**Comment by joel-costigliola** [comment]
Hey Max, thanks for the PR !

I would name the assertions slightly differently by removing `Times` from them and putting the number as the parameter, it would look like :

```java
assertThat(actual).contains(3, "test"); 

assertThat(actual).containsAtLeast(3, "test"); 

assertThat(actual).containsAtMost(3, "test"); 
```

WDYT ?

Cheers

**Comment by mdaniline** [comment]
That sounds good to me :)

**Comment by joel-costigliola** [comment]
Integrated, thanks ! (with some javadoc improvements)

**Comment by joel-costigliola** [comment]
@mdaniline FYI, I have released assertj-guava 3.1.0 version with this feature yesterday.

**Pull request closed without merging**
